--
-- SQLite Version of the current schema
---

-- Clean up
DROP TABLE IF EXISTS run;
DROP TABLE IF EXISTS building;
DROP TABLE IF EXISTS building_calc_attribs;
DROP TABLE IF EXISTS roof_segment;
DROP TABLE IF EXISTS roof_segment_calc_attribs;
DROP TABLE IF EXISTS grid_cell_elevation;
DROP TABLE IF EXISTS grid_cell_calc_attribs;
DROP TABLE IF EXISTS weather_region;
DROP TABLE IF EXISTS hourly_building_energy;

-- v3??
CREATE TABLE run (
    fid INTEGER PRIMARY KEY,
    run_by VARCHAR,
    -- SQLite has a non-standard TIMESTAMP type called DATETIME
    run_date TIMESTAMP,
    -- Optional human readable description of run charateristics
    run_title TEXT,
    -- Major.Minor.Patch semantic version of where the model was at when this was run.
    model_version TEXT,
    -- string of input parameters, geographic area, level of detail, profiles, etc
    -- Can also be considered a scenario, such as a cloudy winter day in Queenstown.
    run_params TEXT
);

-- v1
-- Our static building footprints table, copied from source dataset(s) 
CREATE TABLE building(
    fid INTEGER PRIMARY KEY,
    geom POLYGON_2D,
    weather_region_id INTEGER
);

-- Attributes we calculate to add to the building
CREATE TABLE building_calc_attribs(
    fid INTEGER PRIMARY KEY,
    building_id INTEGER,
    run_id INTEGER,
    -- Electricity generated by solar panels over an average day, using economically viable panel areas.
    viable_solar_gen_kwh_per_day DOUBLE,
    -- Max possible electricity generated if maximizing roof utilization, including low generating panels.
    max_possible_solar_gen_kwh_per_day DOUBLE,
    -- Total energy consumed by the building's devices (the total demand, regardless of source) over an average day.
    building_consumption_kwh_per_day DOUBLE,
    -- Energy exported (sold) to the utility grid over an average day.
    grid_export_kwh_per_day DOUBLE,
    -- Energy consumed (purchased) from the utility grid over an average day.
    grid_import_kwh_per_day DOUBLE,
    -- Percentage of battery size used. One cycle per day may use 80%. 
    -- Day trading (evening and midday) may increase to > 100%.
    battery_use_percent_per_day DOUBLE,
    FOREIGN KEY (building_id) REFERENCES building(fid),
    FOREIGN KEY (run_id) REFERENCES run(fid)
);

-- v2
-- Each flat segment of the roof, with common direction and slope
CREATE TABLE roof_segment(
    fid INTEGER PRIMARY KEY,
    geom POLYGON_2D,
    building_id INTEGER,
    FOREIGN KEY (building_id) REFERENCES building(fid)
);

-- v2
CREATE TABLE roof_segment_calc_attribs (
    fid INTEGER PRIMARY KEY,
    roof_segment_id INTEGER,
    run_id INTEGER,
    -- Electricity generated by solar panels over an average day, using economically viable panel areas.
    viable_solar_gen_kwh_per_day DOUBLE,
    -- Max possible electricity generated if maximizing roof utilization, including low generating panels.
    max_possible_solar_gen_kwh_per_day DOUBLE,
    -- Area of roof segment that can fit solar panels
    usable_roof_segment_area DOUBLE,
    -- Angle off horizon, 0 <= slope < 90 degrees
    slope TINYINT CHECK (slope BETWEEN 0 AND 90),
    -- Direction from truth north, 0 < 360 degrees, technically Azimuth
    direction SMALLINT CHECK (direction BETWEEN 0 AND 359),
    -- Initially, panel details can just be a constant, ~ 20%
    panel_efficiency DOUBLE,
    FOREIGN KEY (roof_segment_id) REFERENCES roof_segment(fid),
    FOREIGN KEY (run_id) REFERENCES run(fid)
);

-- v1
-- Grid or GeoTIFF Sourced from LINZ 1x1m GeoTIFF
-- Limited to flat attributes for GeoTIFF / QGIS UX
-- Missing primary key?
CREATE TABLE grid_cell_elevation (
    -- (lat,long) coordinate
    coord POINT_2D,
    -- Height above sea level (units?)
    elevation INT
);

-- v1
-- Missing foreign key?
CREATE TABLE grid_cell_calc_attribs (
    run_id INTEGER,
    -- Average daily solar energy per m2 (kWh/m2)
    -- Considers latitude, shade, cloudy weather, seasons
    -- Doesn't consider panel efficiency (of ~ 20%)
    solar_irradiation_per_day DOUBLE,
    -- Angle off horizon, 0 <= slope < 90 degrees
    slope TINYINT CHECK (slope BETWEEN 0 AND 90),
    -- Direction from truth north, 0 < 360 degrees, technically Azimuth
    direction SMALLINT CHECK (direction BETWEEN 0 AND 359),
    -- Percentage reduction due to shading.
    -- Averaged across the year.
    avg_shade_factor DOUBLE,
    -- "The fractional reduction in potential solar energy due to atmospheric conditions (clouds, haze, etc.),
    -- typically ranging from 0 to 1. Averaged across the year.
    avg_cloud_loss_factor DOUBLE,
    FOREIGN KEY (run_id) REFERENCES run(fid)
);

-- v1
CREATE TABLE weather_region (
    fid INTEGER PRIMARY KEY,
    -- Geographic footprint of the weather region
    geom POLYGON_2D,
    -- Human readable name for the weather region
    region_name TEXT,
    -- The average daily horizontal solar irradiation in kWh/m^2
    solar_exposure_kwh_sqm DOUBLE,
    -- The fractional reduction in potential solar energy due to atmospheric conditions (clouds, haze, etc.), 
    -- typically ranging from 0 to 1. Averaged across the year.
    avg_cloud_loss_factor DOUBLE
);

-- v3
CREATE TABLE hourly_building_energy (
    fid INTEGER PRIMARY KEY,
    building_id INTEGER,
    run_id INTEGER,
    month TINYINT CHECK (month BETWEEN 1 AND 12),
    hour TINYINT CHECK (hour BETWEEN 0 AND 23),
    viable_solar_gen_kwh_per_hr DOUBLE,
    building_load_kwh_per_hr DOUBLE,
    grid_export_kwh_per_hr DOUBLE,
    grid_import_kwh_per_hr DOUBLE,    
    FOREIGN KEY (building_id) REFERENCES building(fid),
    FOREIGN KEY (run_id) REFERENCES run(fid)
);
